travis:
  secure:
    BINSTAR_TOKEN: WBsxgSU5iT6S3nKk/4pynvoXm1were0JeGtUZLK/YuYrkqt7olvd4iOyKyB6eJXpn/o9HHe5GIBBV10ak7GY9Xs1J9cOpV7rFA1RzMP0mwnBPLU539u/OkNtCyGzpjVgmRjNrDzuu8AxRWv+uR56VcBmB1jwvg6g16kkhhiryg00p018Nxj60w8lGqzBt5BJBIdOK+l6kAUzNew0i8/CxSFdfOBqAb5e2vxsF4JgRMqjR1hkhpKAwrzuFU7wU+QwKlfQyfxloDERL6iRTIzeMaZp86A0QWbnkAtt3GbHX4tdyNpKDUjfcAaNcxup3sLKBaX+3NaEtZs05Qha7/mRqoAaIteLKnUYFJPabayhGEBmTppTvdBjnnhZ/1YgdTAqvRQeXfzgWOuNPiexGAp5EU7LMlglBoFrCQ8wmJmFEL4CvO/Zo1JLTEUz/UjqiUNW2XFl5sjSMwTk62eRytA9yficf2NK8FQxjjgBzMiDgqmAqrx72gF0Y5gntPA/glwRka6QiXE4L+aa7T8VTUXYe0D3YJgZh/bioqeOJVRvQWb9/ExPgra5zK2PIbUIvzRp9NeR0EGn9p3Tw/gLobvy5DUDzD6iolWbBmVjeeL99Ghp1PRUTM73kbXklxmo28kX/6mZX9XwNOS8MX3Vkt8P64sbMdU/5k3ONIzsJ0f5usg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
